- name: Install and start Apache2
  hosts: webserver
  become: true
  tasks:
    - name: Install nginx latest version
      apt: name=nginx state=present
    - name: copy index.html to webserver
      copy:
        src: ./index.html
        dest: /var/www/html
    - name: Nginx is started
      service:
        name: nginx
        state: reloaded
        enabled: true
