---
- name: setup Mysql and restart services
  become: true
  hosts: database
  tasks:
    - name: Install Mysql and dependencies
      package:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: present
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: true
